/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} scale = {0.1}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[-1.31, 0.29, 2.61]} />
        <meshBasicMaterial color={'blue'}/>
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
